---
- hosts: test
  become: True
  tasks:
    - name: Start the container
      docker_container:
        name: testapp
        image: "cranifax/testapp:{{DOCKER_TAG}}"
        state: started
        published_ports:
          - 40.71.214.107:8080:8080
